"""
PIPELINE_CANARY - the detection pipeline itself stopped delivering events.

Inverted logic. Every other rule in this repo alerts because something arrived;
this one alerts because something did NOT. tools/canary.py writes a uniquely
named configmap into the detection-canary namespace every 5 minutes, and that
write is guaranteed to be audited. If none has landed inside the window, the
transport between the apiserver and OpenSearch is broken.

WHY THIS EXISTS
---------------
Zero alerts is ambiguous. It means either "no attacks occurred" or "the pipeline
is dead", and nothing in a clean run distinguishes them. Every other rule in
this repo returns zero in both cases. This rule is what makes zero readable: if
the canary is present, zero means quiet; if it is absent, zero means blind.

WHY T1562.008
-------------
A canary is not an adversary behaviour, and inventing a technique to satisfy the
metadata contract would be the same dishonesty this repo documents everywhere
else. But the mapping is real: an adversary who disables audit logging produces
exactly the observable this rule fires on. Missing telemetry is indistinguishable
from suppressed telemetry, which is the whole argument for alerting on it.

WHAT IT DOES NOT COVER
----------------------
It cannot tell you WHERE the transport broke - Fluent Bit, Kafka, Cribl and the
OpenSearch bulk API all look identical from here. It also cannot, by itself,
distinguish a dead generator from a dead pipeline; run_detections.py uses
canary.py's state file for that. And a total OpenSearch outage is not this
rule at all - the search then fails outright, which run_detections.py reports
separately as "cannot evaluate". See DETECTIONS.md.
"""

from detections.base import Rule, TestCase, deep_get_first, get

NAMESPACE = "detection-canary"
PREFIX = "canary-"
HEARTBEAT_OPS = {"create", "delete"}


class PipelineCanary(Rule):
    id = "PIPELINE_CANARY"
    title = "Detection pipeline heartbeat missing"
    severity = "HIGH"
    owner = "detection-eng"
    description = (
        "No canary heartbeat reached OpenSearch inside the window. The audit "
        "transport is broken, so every other detection in this run is "
        "inconclusive rather than clean. Generated by tools/canary.py."
    )
    runbook = "docs/runbooks/pipeline_canary.md"
    mitre = ["T1562.008"]

    # Runner-only. An absence rule cannot be a native OpenSearch monitor: the
    # rendered condition is `hits.total.value >= threshold`, which inverted
    # means it would fire whenever the pipeline is healthy. deploy.py refuses
    # absence rules explicitly rather than trusting this field alone.
    mode = "runner"
    fires_on = "absence"

    # canary.py beats every 5 minutes. 15 tolerates two missed beats before
    # firing, so a single slow flush or a Cribl restart does not page anyone.
    window_minutes = 15
    threshold = 1

    query = {
        "bool": {
            "filter": [
                {"term": {"resources.type": "configmaps"}},
                {"term": {"resources.namespace": NAMESPACE}},
                {"prefix": {"resources.name": PREFIX}},
            ]
        }
    }

    def rule(self, event):
        """
        Is this event a valid canary heartbeat?

        Note the meaning: for an absence rule, rule() still answers "does this
        event count toward the trigger condition?" - it just counts toward a
        condition that fires when the count is too LOW. The predicate itself is
        ordinary, which is why the fixtures below are real audit events.
        """
        if deep_get_first(event, "resources.type") != "configmaps":
            return False
        if deep_get_first(event, "resources.namespace") != NAMESPACE:
            return False
        name = deep_get_first(event, "resources.name", "")
        if not isinstance(name, str) or not name.startswith(PREFIX):
            return False
        return get(event, "api.operation") in HEARTBEAT_OPS

    def alert_title(self, event):
        """Describes a heartbeat that WAS seen - the healthy 'last seen' line."""
        name = deep_get_first(event, "resources.name", "unknown")
        op = get(event, "api.operation", "?")
        actor = get(event, "actor.user.name", "unknown")
        return f"heartbeat {op} {NAMESPACE}/{name} by {actor}"

    def dedup_key(self, event):
        return f"{self.id}:{deep_get_first(event, 'resources.name', 'unknown')}"

    # Fixtures are real documents captured from the running pipeline, not
    # hand-written approximations.
    tests = [
        TestCase(
            name="real heartbeat create is a valid beat",
            expect=True,
            event={
                "@timestamp": "2026-08-25T23:15:58.571Z",
                "class_uid": 6003,
                "api": {"operation": "create"},
                "activity_id": 1,
                "status_id": 1,
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "canary-1787699757", "type": "configmaps",
                               "namespace": NAMESPACE}],
            },
        ),
        TestCase(
            name="the paired delete also counts, so a lost create still beats",
            expect=True,
            event={
                "@timestamp": "2026-08-25T23:15:58.808Z",
                "class_uid": 6003,
                "api": {"operation": "delete"},
                "activity_id": 4,
                "status_id": 1,
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "canary-1787699757", "type": "configmaps",
                               "namespace": NAMESPACE}],
            },
        ),
        TestCase(
            name="same-named configmap in another namespace is not our canary",
            expect=False,
            event={
                "api": {"operation": "create"},
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "canary-1787699757", "type": "configmaps",
                               "namespace": "default"}],
            },
        ),
        TestCase(
            name="an unrelated configmap in the canary namespace is not a beat",
            expect=False,
            event={
                "api": {"operation": "create"},
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "app-config", "type": "configmaps",
                               "namespace": NAMESPACE}],
            },
        ),
        TestCase(
            name="a read of the canary is not a beat - and is dropped anyway (A3)",
            expect=False,
            event={
                "api": {"operation": "get"},
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "canary-1787699757", "type": "configmaps",
                               "namespace": NAMESPACE}],
            },
        ),
        TestCase(
            name="a secret named like the canary does not count",
            expect=False,
            event={
                "api": {"operation": "create"},
                "actor": {"user": {"name": "system:admin"}},
                "resources": [{"name": "canary-1787699757", "type": "secrets",
                               "namespace": NAMESPACE}],
            },
        ),
        TestCase(
            name="malformed event with no resources block does not crash",
            expect=False,
            event={"api": {"operation": "create"}},
        ),
    ]
